### ISSUE TITLE
Question about source code

### ISSUE THREAD

**Issue by ovalseven8** [saltyrtc/saltyrtc-client-java#119]
I skimmed a little through the code and wonder if `CLOSING_NORMAL` is missing here? However, I am not that familiar with the SaltyRTC protocol.

https://github.com/saltyrtc/saltyrtc-client-java/blob/f988042bc5fa2196014ba8a5d6d87104eab24554/src/main/java/org/saltyrtc/client/signaling/CloseCode.java#L90-L94

**Comment by dbrgn** [comment]
Hm, yeah, I think that's missing indeed! The variable is only used in `ValidationHelper.validateCloseCode`, but it could still potentially result in an exception during teardown of the connection.

**Comment by ovalseven8** [comment]
You can assign me if you want.

**Comment by dbrgn** [comment]
@ovalseven8 if you're up for a pull request, sure! That would be welcome.
