### ISSUE TITLE
Question: Allow Kotlin?

### ISSUE THREAD

**Issue by ovalseven8** [saltyrtc/saltyrtc-client-java#127]
I wanted to ask if you would like this library to be 100% Java or if you allow Kotlin for future changes?

What's true is that Kotlin would require the Kotlin runtime whats basically nothing else than additional classes (.jar files).

<img src="https://tedhagos.com/images/kotlin-compilation-process.png" width="500">

I know that this library is used for Android apps, so memory and disk usage is important too. So [ProGuard](https://en.wikipedia.org/wiki/ProGuard_(software)) might help in this case.

**Comment by dbrgn** [comment]
While I like Kotlin, I'd prefer to currently keep this library plain-java to avoid dragging the runtime into every application that uses this library.

(This decision might be different if we would start from scratch, but now that the codebase is already written I don't see a big advantage in including Kotlin.)
