### ISSUE TITLE
Determining of first common task

### ISSUE THREAD

**Issue by dbrgn** [saltyrtc/saltyrtc-client-java#24]
> The initiator SHALL continue by comparing the provided tasks to its own Array of available tasks and MUST choose the first common task from both Arrays. 

In the following case, which one is the first common task?

    initiator: ['webrtc', 'ortc']
    responder: ['ortc', 'webrtc']

I assume it's `webrtc`, as the initiator is the one that chooses, so it gets the pick.

What about this wording?

> The initiator SHALL continue by comparing the provided tasks to its own Array of available tasks. It MUST choose the first task in its own list of available tasks that is also contained in the list of provided tasks.

That would mean that in the example above, `webrtc` is chosen.

It would also mean that in the following case...

    initiator: ['webrtc', 'ortc', 'email']
    responder: ['ortc', 'websockets', 'email', 'sms', 'carrier-pigeons', 'webrtc']

...webrtc would be chosen, even though webrtc is the least preferred task of the responder, and even though ortc would look like a good match in this case.

@lgrahl what are your thoughts?

**Comment by dbrgn** [comment]
This also seems to be the algorithm that ALPN uses:

https://tools.ietf.org/html/rfc7301#section-3.2

>    It is expected that a server will have a list of protocols that it
>    supports, in preference order, and will only select a protocol if the
>    client supports it.  In that case, the server SHOULD select the most
>    highly preferred protocol that it supports and that is also
>    advertised by the client.  In the event that the server supports no
>    protocols that the client advertises, then the server SHALL respond
>    with a fatal "no_application_protocol" alert.

**Comment by lgrahl** [comment]
I'd do it [that way](https://github.com/aaugustin/websockets/blob/181acf3e29499ecff61b5e6892d73bae5332292e/websockets/server.py#L198:L207). But I have no idea how to describe this properly.

**Comment by dbrgn** [comment]
I'm not sure if that could have some undesired side effects coming from the fact that you're using the sum of both indexes... And it's hard to describe, and to understand intuitively :)

But it might yield better results in some cases. Do you know of a way to prove that it yields better results in the majority or all of the cases?

**Comment by lgrahl** [comment]
Hm, it's intuitive to me. You will probably have to test it out but I'm pretty certain it will yield good results and is very easy to implement. I wouldn't specify it in the spec. Just something like:

> the initiator SHALL select the most highly preferred protocol that it supports which is also advertised by the responder

(I'll file an issue about the subprotocol downgrade detection issue though. And I'll fix that immediately.)

**Comment by dbrgn** [comment]
> the initiator SHALL select the most highly preferred protocol that it supports which is also advertised by the responder.

That would result in the ALPN algorithm though. Your approach does not follow that description. It would probably choose a random entry in the case of my first example, and `ortc` in the second example, which is not the most highly preferred protocol of the initiator that is also advertised by the responder.

**Comment by lgrahl** [comment]
So, basically ALPN is what we've described in the spec?

```
server_subprotocols = set(server_subprotocols)
chosen = next((proto for proto in client_subprotocols if proto in server_subprotocols))
```

I'd be okay with that if you are. I don't know what would be the best algorithm. There probably isn't one.

**Comment by dbrgn** [comment]
Yes, this way or the other way around, depending on whether the user or the server should have the last word.

In more traditional code:

```java
for (String task : initiatorTasks) {
    if (responderTasks.contains(task)) {
        return task;
    }
    return null;
}
```

I'd probably choose this approach over the other one, because it's simpler to grasp. And because:

> There probably isn't one.

In any case, should we put this wording in the spec?

> The initiator SHALL continue by comparing the provided tasks to its own Array of supported tasks. It MUST choose the first task in its own list of supported tasks that is also contained in the list of supported tasks provided by the responder.

If ALPN uses that, it can't be too wrong.

**Comment by lgrahl** [comment]
Isn't that pretty much exactly what is in the spec at the moment?

> The initiator SHALL continue by comparing the provided tasks to its own `Array` of available tasks and MUST choose the first common task from both `Arrays`.

**Comment by dbrgn** [comment]
No, "the first common task" does not specify *how* to find that first common task :) See first example in the original post, is it webrtc or ortc?

I'll create a PR with the change tomorrow.
