### ISSUE TITLE
How to connect clients across NAT?

### ISSUE THREAD

**Issue by sibirchakraborty** [saltyrtc/saltyrtc-client-java#69]
How to connect clients across NAT?

Client 1 -> Private IP 1 (Initiator)
Client 2 -> Private IP 2 (Receiver)

Also, how is ICE server configured?

**Comment by lgrahl** [comment]
I guess what you want to create is a WebRTC peer connection which connects client 1 and client 2 using ICE. That's not SaltyRTC. SaltyRTC **is neither** a WebRTC implementation **nor** a wrapper to WebRTC. You cannot connect a peer-to-peer connection from A to B with SaltyRTC alone. SaltyRTC is a general purpose signalling protocol which can be used for WebRTC using the SaltyRTC WebRTC Task to **exchange signalling data** (such as *offer*, *answer* and *candidates* encoded in SDP) needed to set up a WebRTC peer-to-peer connection. However, configuration and setup of WebRTC is outside the scope of SaltyRTC. I hope this clears things up a bit.

Check out the code of our [demo application](https://github.com/saltyrtc/saltyrtc-demo) which probably does what you want to do.

**Comment by lgrahl** [comment]
I closed the issue because it hasn't anything to do with SaltyRTC. But it's perfectly fine if you want to ask further questions for clearing things up as we don't have any other channel where you can ask these questions. (@dbrgn: maybe it's time for a reddit channel or IRC... or a Threema group? Suggestions?)

**Comment by dbrgn** [comment]
We could also go hipster and use https://gitter.im/.

**Comment by lgrahl** [comment]
Sure, why not: https://gitter.im/saltyrtc
